#:kivy 2.0.0

<SignupScreen>:
	name: 'signup'
	username: username
	password: password
	confirmPassword: confirmPassword
	MDCard:
		size_hint: None, None
		size: 300, 450
		pos_hint: {"center_x": 0.5, "center_y": 0.5}
		elevation: 10
		padding: [50, 50, 50, 25]
		spacing: 20
		orientation: 'vertical'

		MDLabel:
			text: 'Signup'
			halign: 'center'
			font_size: 35

		MDTextField:
			id: username
			hint_text: 'Username' 
			helper_text: 'Enter username'
			helper_text_mode: 'on_focus'
			font_size: 20
			width: 200
			write_tab: False
			on_text_validate: root.submit()

		MDTextField:
			id: password
			hint_text: 'Password' 
			helper_text: 'Enter password'
			helper_text_mode: 'on_focus'
			password: True
			font_size: 20
			width: 200
			write_tab: False
			on_text_validate: root.submit()

		MDTextField:
			id: confirmPassword
			hint_text: 'Confirm Password' 
			helper_text: 'Confirm password'
			helper_text_mode: 'on_focus'
			password: True
			font_size: 20
			width: 200
			write_tab: False
			on_text_validate: root.submit()

		MyButton:
			text: 'Signup'
			pos_hint: {'center_x': .5}
			size_hint_x: 1
			on_release: root.submit()
		
		MyButton:
			text: 'Sign In'
			pos_hint: {'center_x': .5}
			size_hint_x: 1
			on_release: 
				root.gotoSignin()